2024-01-20 00:50:21,850: root: INFO: MyStrategy : Executing the initialize lifecycle method
2024-01-20 00:50:23,341: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2024-01-20 00:50:23,342: root: INFO: MyStrategy : Executing the before_market_opens lifecycle method
2024-01-20 00:50:23,343: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2024-01-20 00:50:23,343: root: INFO: MyStrategy : Executing the before_starting_trading lifecycle method
2024-01-20 00:50:23,344: root: INFO: [34mMyStrategy : Executing the on_trading_iteration lifecycle method at 2024-01-20 00:50:23[0m
2024-01-20 00:50:23,344: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-01-20 00:50:23,344: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-01-20 00:50:25,057: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'take_profit'
2024-01-20 00:50:25,057: root: ERROR: Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 829, in run
    self._run_trading_session()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 780, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 274, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 298, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 87, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 378, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\OneDrive\Desktop\machine learning\stockbot\trade1.py", line 50, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'take_profit'

2024-01-20 00:50:25,070: root: INFO: MyStrategy : Executing the on_bot_crash event method
2024-01-20 00:50:25,083: root: INFO: Backtesting finished
2024-01-20 00:50:25,087: root: WARNING: Cannot plot returns because the strategy returns are missing
2024-01-20 00:50:25,330: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
2024-01-20 00:50:25,330: backtest_stats: INFO: Backtest took 0:00:03.482184 for a speed of 0.000
